<?php
namespace App\Http\Controllers;
use App\Models\Cliente;
use App\Services\FitFamilyContext;
use App\Support\Audit;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
class FitFamilyController extends Controller {
 public function catalog(Request $request,FitFamilyContext $context):JsonResponse{$e=$context->resolve($request);$cats=DB::table('fitfamily_categorias')->where('empresa_id',$e->id)->where('activo',true)->orderBy('orden')->orderBy('nombre')->get();$products=DB::table('fitfamily_productos')->where('empresa_id',$e->id)->where('visible',true)->where('disponible',true)->where('stock','>',0)->orderBy('nombre')->get()->groupBy('categoria_id');$cats->transform(fn($c)=>tap($c,fn($x)=>$x->productos=$products->get($c->id,collect())->values()));$config=DB::table('fitfamily_configuracion')->where('empresa_id',$e->id)->pluck('valor','clave');return response()->json(['data'=>$cats,'configuracion'=>$config]);}
 public function category(Request $request,string $slug,FitFamilyContext $context):JsonResponse{$e=$context->resolve($request);$c=DB::table('fitfamily_categorias')->where('empresa_id',$e->id)->where('slug',$slug)->where('activo',true)->first();abort_unless($c,404,'Categoría no encontrada.');$c->productos=DB::table('fitfamily_productos')->where('empresa_id',$e->id)->where('categoria_id',$c->id)->where('visible',true)->where('disponible',true)->where('stock','>',0)->orderBy('nombre')->get();$config=DB::table('fitfamily_configuracion')->where('empresa_id',$e->id)->pluck('valor','clave');return response()->json(['data'=>$c,'configuracion'=>$config]);}
 private function admin(Request $r,FitFamilyContext $c){$e=$c->resolve($r);$c->assertAdmin($r,$e);return $e;}
 public function dashboard(Request $r,FitFamilyContext $c):JsonResponse{$e=$this->admin($r,$c);$q=DB::table('fitfamily_pedidos')->where('empresa_id',$e->id);$cnt=$q->select('estado',DB::raw('COUNT(*) total'))->groupBy('estado')->pluck('total','estado');return response()->json(['data'=>['productos'=>DB::table('fitfamily_productos')->where('empresa_id',$e->id)->count(),'productos_disponibles'=>DB::table('fitfamily_productos')->where('empresa_id',$e->id)->where('visible',true)->where('disponible',true)->where('stock','>',0)->count(),'clientes'=>$q->distinct('cliente_id')->count('cliente_id'),'pedidos'=>$q->count(),'pedidos_pendientes'=>(int)($cnt['pendiente']??0),'pedidos_en_proceso'=>(int)(($cnt['confirmado']??0)+($cnt['preparando']??0)),'pedidos_entregados'=>(int)($cnt['entregado']??0),'pedidos_cancelados'=>(int)($cnt['cancelado']??0),'ventas'=>number_format((float)$q->whereIn('estado',['confirmado','preparando','entregado'])->sum('total'),2,'.',''),'stock_bajo'=>DB::table('fitfamily_productos')->where('empresa_id',$e->id)->where('visible',true)->whereColumn('stock','<=','stock_minimo')->orderBy('stock')->limit(8)->get(['id','nombre','stock','stock_minimo','disponible']),'ultimos_pedidos'=>DB::table('fitfamily_pedidos as p')->join('clientes as c','c.id','=','p.cliente_id')->leftJoin('fitfamily_pagos as pg','pg.pedido_id','=','p.id')->where('p.empresa_id',$e->id)->orderByDesc('p.id')->limit(8)->get(['p.id','p.numero','p.estado','p.total','p.created_at','c.nombre as cliente_nombre','pg.metodo_pago','pg.estado as pago_estado','pg.monto'])]]);}
 public function categorias(Request $r,FitFamilyContext $c):JsonResponse{$e=$this->admin($r,$c);return response()->json(['data'=>DB::table('fitfamily_categorias')->where('empresa_id',$e->id)->orderBy('orden')->orderBy('nombre')->get()]);}
 public function storeCategoria(Request $r,FitFamilyContext $c):JsonResponse{$e=$this->admin($r,$c);$d=$r->validate(['nombre'=>'required|string|max:120','slug'=>'nullable|string|max:140','descripcion'=>'nullable|string','imagen_url'=>'nullable|string|max:2048','activo'=>'sometimes|boolean','orden'=>'sometimes|integer|min:0']);$s=Str::slug($d['slug']??$d['nombre']);abort_if(DB::table('fitfamily_categorias')->where('empresa_id',$e->id)->where('slug',$s)->exists(),422,'El slug de la categoría ya existe.');$id=DB::table('fitfamily_categorias')->insertGetId($d+['empresa_id'=>$e->id,'slug'=>$s,'activo'=>$d['activo']??true,'orden'=>$d['orden']??0,'created_at'=>now(),'updated_at'=>now()]);return response()->json(['data'=>DB::table('fitfamily_categorias')->find($id)],201);}
 public function updateCategoria(Request $r,int $id,FitFamilyContext $c):JsonResponse{$e=$this->admin($r,$c);abort_unless(DB::table('fitfamily_categorias')->where('empresa_id',$e->id)->where('id',$id)->exists(),404);$d=$r->validate(['nombre'=>'required|string|max:120','slug'=>'nullable|string|max:140','descripcion'=>'nullable|string','imagen_url'=>'nullable|string|max:2048','activo'=>'sometimes|boolean','orden'=>'sometimes|integer|min:0']);$s=Str::slug($d['slug']??$d['nombre']);abort_if(DB::table('fitfamily_categorias')->where('empresa_id',$e->id)->where('slug',$s)->where('id','!=',$id)->exists(),422,'El slug de la categoría ya existe.');DB::table('fitfamily_categorias')->where('id',$id)->update($d+['slug'=>$s,'updated_at'=>now()]);return response()->json(['data'=>DB::table('fitfamily_categorias')->find($id)]);}
 public function productos(Request $r,FitFamilyContext $c):JsonResponse{$e=$this->admin($r,$c);return response()->json(['data'=>DB::table('fitfamily_productos as p')->join('fitfamily_categorias as c','c.id','=','p.categoria_id')->where('p.empresa_id',$e->id)->orderByDesc('p.id')->get(['p.*','c.nombre as categoria_nombre'])]);}
 public function storeProducto(Request $r,FitFamilyContext $c):JsonResponse{$e=$this->admin($r,$c);$d=$r->validate(['categoria_id'=>'required|integer','nombre'=>'required|string|max:180','slug'=>'nullable|string|max:200','descripcion'=>'nullable|string','precio'=>'required|numeric|min:0','stock'=>'required|integer|min:0','stock_minimo'=>'sometimes|integer|min:0','imagen_url'=>'nullable|string|max:2048','disponible'=>'sometimes|boolean','visible'=>'sometimes|boolean']);abort_unless(DB::table('fitfamily_categorias')->where('id',$d['categoria_id'])->where('empresa_id',$e->id)->exists(),422,'La categoría no pertenece a esta empresa.');$s=Str::slug($d['slug']??$d['nombre']);abort_if(DB::table('fitfamily_productos')->where('empresa_id',$e->id)->where('slug',$s)->exists(),422,'El slug del producto ya existe.');$id=DB::table('fitfamily_productos')->insertGetId($d+['empresa_id'=>$e->id,'slug'=>$s,'stock_minimo'=>$d['stock_minimo']??5,'disponible'=>(bool)($d['disponible']??true)&&$d['stock']>0,'visible'=>$d['visible']??true,'created_at'=>now(),'updated_at'=>now()]);return response()->json(['data'=>DB::table('fitfamily_productos')->find($id)],201);}
 public function updateProducto(Request $r,int $id,FitFamilyContext $c):JsonResponse{$e=$this->admin($r,$c);abort_unless(DB::table('fitfamily_productos')->where('empresa_id',$e->id)->where('id',$id)->exists(),404);$d=$r->validate(['categoria_id'=>'required|integer','nombre'=>'required|string|max:180','slug'=>'nullable|string|max:200','descripcion'=>'nullable|string','precio'=>'required|numeric|min:0','stock'=>'required|integer|min:0','stock_minimo'=>'required|integer|min:0','imagen_url'=>'nullable|string|max:2048','disponible'=>'required|boolean','visible'=>'required|boolean']);abort_unless(DB::table('fitfamily_categorias')->where('id',$d['categoria_id'])->where('empresa_id',$e->id)->exists(),422,'La categoría no pertenece a esta empresa.');$s=Str::slug($d['slug']??$d['nombre']);abort_if(DB::table('fitfamily_productos')->where('empresa_id',$e->id)->where('slug',$s)->where('id','!=',$id)->exists(),422,'El slug del producto ya existe.');$d['disponible']=(bool)$d['disponible']&&$d['stock']>0;DB::table('fitfamily_productos')->where('id',$id)->update($d+['slug'=>$s,'updated_at'=>now()]);return response()->json(['data'=>DB::table('fitfamily_productos')->find($id)]);}
 public function toggleProducto(Request $r,int $id,FitFamilyContext $c):JsonResponse{$e=$this->admin($r,$c);$p=DB::table('fitfamily_productos')->where('empresa_id',$e->id)->where('id',$id)->first();abort_unless($p,404);DB::table('fitfamily_productos')->where('id',$id)->update(['visible'=>!$p->visible,'updated_at'=>now()]);return response()->json(['data'=>['id'=>$id,'visible'=>!$p->visible]]);}
 public function clientes(Request $r,FitFamilyContext $c):JsonResponse{$e=$this->admin($r,$c);$ids=DB::table('fitfamily_pedidos')->where('empresa_id',$e->id)->distinct()->pluck('cliente_id');return response()->json(['data'=>Cliente::query()->whereIn('id',$ids)->orderByDesc('id')->get()]);}
 public function pedidos(Request $r,FitFamilyContext $c):JsonResponse{$e=$this->admin($r,$c);$rows=DB::table('fitfamily_pedidos as p')->join('clientes as c','c.id','=','p.cliente_id')->leftJoin('fitfamily_pagos as pg','pg.pedido_id','=','p.id')->where('p.empresa_id',$e->id)->orderByDesc('p.id')->get(['p.*','c.nombre as cliente_nombre','c.telefono','c.whatsapp','c.correo','pg.metodo_pago','pg.estado as pago_estado','pg.monto','pg.referencia']);foreach($rows as $x)$x->detalles=DB::table('fitfamily_pedido_detalles')->where('pedido_id',$x->id)->get();return response()->json(['data'=>$rows]);}
 public function updatePedido(Request $r,int $id,FitFamilyContext $c):JsonResponse{$e=$this->admin($r,$c);$d=$r->validate(['estado'=>[Rule::in(['pendiente','confirmado','preparando','entregado','cancelado'])]]);$p=DB::table('fitfamily_pedidos')->where('empresa_id',$e->id)->where('id',$id)->first();abort_unless($p,404);$allowed=['pendiente'=>['confirmado','cancelado'],'confirmado'=>['preparando','cancelado'],'preparando'=>['entregado'],'entregado'=>[],'cancelado'=>[]];abort_unless(in_array($d['estado'],$allowed[$p->estado]??[],true),422,'Transición de pedido no permitida.');DB::transaction(function()use($p,$d,$r){if($d['estado']==='cancelado')foreach(DB::table('fitfamily_pedido_detalles')->where('pedido_id',$p->id)->get() as $det){$prod=DB::table('fitfamily_productos')->lockForUpdate()->find($det->producto_id);if($prod)DB::table('fitfamily_productos')->where('id',$prod->id)->update(['stock'=>$prod->stock+$det->cantidad,'disponible'=>true,'updated_at'=>now()]);}DB::table('fitfamily_pedidos')->where('id',$p->id)->update(['estado'=>$d['estado'],'updated_at'=>now()]);Audit::log($r,'fitfamily_pedido_estado_actualizado',null,'Estado de pedido FitFamily actualizado.',['pedido_id'=>$p->id,'estado_anterior'=>$p->estado,'estado_nuevo'=>$d['estado']]);});return response()->json(['message'=>'Estado del pedido actualizado.']);}
 public function config(Request $r,FitFamilyContext $c):JsonResponse{$e=$this->admin($r,$c);return response()->json(['data'=>DB::table('fitfamily_configuracion')->where('empresa_id',$e->id)->pluck('valor','clave')]);}
 public function saveConfig(Request $r,FitFamilyContext $c):JsonResponse{$e=$this->admin($r,$c);$d=$r->validate(['configuracion'=>'required|array']);foreach($d['configuracion'] as $k=>$v)DB::table('fitfamily_configuracion')->updateOrInsert(['empresa_id'=>$e->id,'clave'=>$k],['valor'=>is_scalar($v)?(string)$v:json_encode($v),'created_at'=>now(),'updated_at'=>now()]);return $this->config($r,$c);}
 private function cart(Request $r,int $eid){$x=DB::table('fitfamily_carritos')->where('empresa_id',$eid)->where('usuario_id',$r->user()->id)->where('estado','activo')->first();if($x)return $x;$id=DB::table('fitfamily_carritos')->insertGetId(['empresa_id'=>$eid,'usuario_id'=>$r->user()->id,'estado'=>'activo','created_at'=>now(),'updated_at'=>now()]);return DB::table('fitfamily_carritos')->find($id);}
 private function payload($cart):array{$items=DB::table('fitfamily_carrito_items as i')->join('fitfamily_productos as p','p.id','=','i.producto_id')->where('i.carrito_id',$cart->id)->get(['i.id','i.producto_id','p.nombre','p.imagen_url','i.cantidad','i.precio_unitario','p.stock']);$items->transform(fn($i)=>tap($i,fn($x)=>$x->subtotal=number_format($x->cantidad*(float)$x->precio_unitario,2,'.','')));$total=$items->sum(fn($i)=>(float)$i->subtotal);return ['id'=>$cart->id,'estado'=>$cart->estado,'items'=>$items,'cantidad_items'=>$items->sum('cantidad'),'total'=>number_format($total,2,'.','')];}
 public function cartIndex(Request $r,FitFamilyContext $c):JsonResponse{$e=$c->resolve($r);return response()->json(['data'=>$this->payload($this->cart($r,$e->id))]);}
 public function history(Request $r,FitFamilyContext $c):JsonResponse{$e=$c->resolve($r);$u=$r->user();$client=Cliente::query()->whereKey($u->cliente_id)->first()?:Cliente::query()->where('correo',$u->correo)->first();if(!$client)return response()->json(['data'=>[]]);$rows=DB::table('fitfamily_pedidos')->where('empresa_id',$e->id)->where('cliente_id',$client->id)->orderByDesc('id')->get();foreach($rows as $x){$x->detalles=DB::table('fitfamily_pedido_detalles')->where('pedido_id',$x->id)->get();$x->pago=DB::table('fitfamily_pagos')->where('pedido_id',$x->id)->first();}return response()->json(['data'=>$rows]);}
 public function addToCart(Request $r,FitFamilyContext $c):JsonResponse{$e=$c->resolve($r);$d=$r->validate(['producto_id'=>'required|integer','cantidad'=>'required|integer|min:1|max:99']);$p=DB::table('fitfamily_productos')->where('empresa_id',$e->id)->where('id',$d['producto_id'])->first();abort_unless($p&&$p->visible&&$p->disponible,422,'El producto no está disponible.');$cart=$this->cart($r,$e->id);$item=DB::table('fitfamily_carrito_items')->where('carrito_id',$cart->id)->where('producto_id',$p->id)->first();$qty=($item->cantidad??0)+$d['cantidad'];abort_if($qty>$p->stock,422,'No hay suficiente stock.');if($item)DB::table('fitfamily_carrito_items')->where('id',$item->id)->update(['cantidad'=>$qty,'precio_unitario'=>$p->precio]);else DB::table('fitfamily_carrito_items')->insert(['carrito_id'=>$cart->id,'producto_id'=>$p->id,'cantidad'=>$qty,'precio_unitario'=>$p->precio]);return response()->json(['message'=>'Producto agregado al carrito.','data'=>$this->payload($cart)],201);}
 public function updateCart(Request $r,int $itemId,FitFamilyContext $c):JsonResponse{$e=$c->resolve($r);$d=$r->validate(['cantidad'=>'required|integer|min:1|max:99']);$cart=$this->cart($r,$e->id);$item=DB::table('fitfamily_carrito_items as i')->join('fitfamily_productos as p','p.id','=','i.producto_id')->where('i.carrito_id',$cart->id)->where('i.id',$itemId)->first();abort_unless($item,404);abort_if($d['cantidad']>$item->stock,422,'No hay suficiente stock.');DB::table('fitfamily_carrito_items')->where('id',$itemId)->update(['cantidad'=>$d['cantidad'],'precio_unitario'=>$item->precio]);return response()->json(['data'=>$this->payload($cart)]);}
 public function deleteCart(Request $r,int $itemId,FitFamilyContext $c):JsonResponse{$e=$c->resolve($r);$cart=$this->cart($r,$e->id);DB::table('fitfamily_carrito_items')->where('carrito_id',$cart->id)->where('id',$itemId)->delete();return response()->json(['data'=>$this->payload($cart)]);}
 public function checkout(Request $r,FitFamilyContext $c):JsonResponse{$e=$c->resolve($r);$d=$r->validate(['telefono'=>'nullable|string|max:40','whatsapp'=>'nullable|string|max:40','direccion'=>'nullable|string|max:250','notas'=>'nullable|string|max:1000','metodo_pago'=>['required',Rule::in(['efectivo','transferencia','qr'])]]);$order=DB::transaction(function()use($r,$e,$d){$cart=$this->cart($r,$e->id);$items=DB::table('fitfamily_carrito_items')->where('carrito_id',$cart->id)->lockForUpdate()->get();abort_if($items->isEmpty(),422,'El carrito está vacío.');$u=$r->user();$client=Cliente::query()->whereKey($u->cliente_id)->first()?:Cliente::query()->where('correo',$u->correo)->first();if(!$client)$client=Cliente::create(['nombre'=>$u->nombre,'correo'=>$u->correo,'telefono'=>$u->telefono,'estado'=>'activo','canal_origen'=>'fitfamily']);$client->fill(['telefono'=>$d['telefono']??$client->telefono,'whatsapp'=>$d['whatsapp']??$client->whatsapp,'direccion'=>$d['direccion']??$client->direccion])->save();$subtotal=0;foreach($items as $i){$p=DB::table('fitfamily_productos')->lockForUpdate()->find($i->producto_id);abort_unless($p&&$p->empresa_id==$e->id&&$p->visible&&$p->disponible,422,'Un producto ya no está disponible.');abort_if($i->cantidad>$p->stock,422,'Stock insuficiente para '.$p->nombre.'.');$subtotal+=$i->cantidad*(float)$p->precio;}$pid=DB::table('fitfamily_pedidos')->insertGetId(['empresa_id'=>$e->id,'cliente_id'=>$client->id,'numero'=>'FF-'.now()->format('YmdHis').'-'.Str::upper(Str::random(4)),'estado'=>'pendiente','subtotal'=>$subtotal,'total'=>$subtotal,'notas'=>$d['notas']??null,'created_at'=>now(),'updated_at'=>now()]);foreach($items as $i){$p=DB::table('fitfamily_productos')->lockForUpdate()->find($i->producto_id);DB::table('fitfamily_pedido_detalles')->insert(['pedido_id'=>$pid,'producto_id'=>$p->id,'nombre_producto'=>$p->nombre,'cantidad'=>$i->cantidad,'precio_unitario'=>$p->precio,'subtotal'=>$i->cantidad*(float)$p->precio]);DB::table('fitfamily_productos')->where('id',$p->id)->update(['stock'=>$p->stock-$i->cantidad,'disponible'=>($p->stock-$i->cantidad)>0,'updated_at'=>now()]);}DB::table('fitfamily_pagos')->insert(['pedido_id'=>$pid,'metodo_pago'=>$d['metodo_pago'],'estado'=>'pendiente','monto'=>$subtotal,'created_at'=>now(),'updated_at'=>now()]);DB::table('fitfamily_carritos')->where('id',$cart->id)->update(['estado'=>'convertido','updated_at'=>now()]);DB::table('fitfamily_carrito_items')->where('carrito_id',$cart->id)->delete();return DB::table('fitfamily_pedidos')->find($pid);});return response()->json(['message'=>'Pedido creado correctamente.','data'=>$order],201);}
}
